language: python
python:
  - '3.5'
  - '3.6'

install:
  - pip install -r requirements.txt

script:
  ./setup.py test

deploy:
  provider: pypi
  distributions: "sdist bdist_wheel"
  user: jayme-pypi
  password:
    secure: OVzVLeEFwPLtrsYaGjkhv5r/47Z8T4JOw6qxULDltaueqKlVszl5cuxo7Tgt41NI71fcTbOH+OegIANNaAa7utwihhnJLBLwwvTQJ5qHVh8O7QRgC1NyHILaw8lAyQKtHKCOBSZ/EpyQXJZ8sKrxvJ9IgkPL0RSFy1FWBxXtYhaDTfdRpIdbs+G8X/UcTgtHW8zhtJC5qFE9Yu17SV8NDWMz/dOHGPnlCoxQYaVZ3duVJ3gNdN0LFjj+Tk9p71nZa4L7H/ufxBO1r1DHRPsRaXCR7HKQ+9qsmO1Q2bggPOb9LqjwZS7HZIvbrxsfSceF+figMVAe/YajoJZ8tva+0Bdinl55RXeIp30ZhLG64EcGLsPCZv6PNsmvubYl0SHvOUZjv16zxH/HlMemoHVg6yuIt99p/L/KHhaYU2BVyMCNa9GdCOJ/awMYjxB2HhAWKO0j3sdYcaDiHM1/84fzbWNQwpxcVcD6eOE5K+I9Q5gSvPcbafyfrbraNK6s5cUUQcnh4jemuyPuMpHkU01NWLkvKjxX4ivislZ8CYVAKKjRFWsbPvC8BN5j8exxxi2KJRLftTOQXzzwX6AgScMDr0hHBzU6jFfcv/V5jecROSCIxye2NihxvDw2r1EtP9ReFpF/OgeQwmV4quXXWxtTapOJdS6Jsjx20/vRnDZS0Ak=
  on:
    tags: true
