language: python

matrix:
  include:
    - python: 3.5
    - python: 3.6
      env: LATEST=true

install:
  - pip install -r requirements.txt

script:
  ./setup.py test

deploy:
  - provider: pypi
    skip_cleanup: true
    distributions: "sdist bdist_wheel"
    user: jayme-pypi
    password:
      secure: OVzVLeEFwPLtrsYaGjkhv5r/47Z8T4JOw6qxULDltaueqKlVszl5cuxo7Tgt41NI71fcTbOH+OegIANNaAa7utwihhnJLBLwwvTQJ5qHVh8O7QRgC1NyHILaw8lAyQKtHKCOBSZ/EpyQXJZ8sKrxvJ9IgkPL0RSFy1FWBxXtYhaDTfdRpIdbs+G8X/UcTgtHW8zhtJC5qFE9Yu17SV8NDWMz/dOHGPnlCoxQYaVZ3duVJ3gNdN0LFjj+Tk9p71nZa4L7H/ufxBO1r1DHRPsRaXCR7HKQ+9qsmO1Q2bggPOb9LqjwZS7HZIvbrxsfSceF+figMVAe/YajoJZ8tva+0Bdinl55RXeIp30ZhLG64EcGLsPCZv6PNsmvubYl0SHvOUZjv16zxH/HlMemoHVg6yuIt99p/L/KHhaYU2BVyMCNa9GdCOJ/awMYjxB2HhAWKO0j3sdYcaDiHM1/84fzbWNQwpxcVcD6eOE5K+I9Q5gSvPcbafyfrbraNK6s5cUUQcnh4jemuyPuMpHkU01NWLkvKjxX4ivislZ8CYVAKKjRFWsbPvC8BN5j8exxxi2KJRLftTOQXzzwX6AgScMDr0hHBzU6jFfcv/V5jecROSCIxye2NihxvDw2r1EtP9ReFpF/OgeQwmV4quXXWxtTapOJdS6Jsjx20/vRnDZS0Ak=
    on:
      repo: jayme-github/pysonio
      tags: true
      condition: "$LATEST = true"
  - provider: script
    skip_cleanup: true
    script:
       - find .
    on:
      repo: jayme-github/pysonio
      tags: true
      condition: "$LATEST = true"
  - provider: releases
    skip_cleanup: true
    api_key:
      secure: G8islO8E/lfgDsy8vffCmaXHt51c7mBio38Lqc8jNFH/jqYlhlegn1J895fYhYs/mZhHtZgGzJjS1ibU/dNwbNsVv2stjyVPgvF0/+Nv6VI4wsML2BiZxb5CapkZSKGekQAaiQ2qamdr6IO9n+/DO1dtynUsTzPjw6+AFgYQTwtWbFZwf7qOMJwYORuPgbaPhtogx1KYlLrQZ36oVpCkBt6mpiixvO9M6YsgQg29BX6Oxk0uZxTuyOGHDaocqF2A6FuL59YPRw9cgMawOIVVFW4oh9Pi1ALtE0ZK7GdJl5RyFnYhp3dKE9sIn1yDw+/QmmGtJo7O5FgcbdBuqEG5x7mQ5A5tHJLSzKBGogwLNRuuGQhybZGKxNn7VQcyBD6wi88p9tYsN7Uj0DEbKGCvx2pw0Sqd/4XLSM4r7ZqTzcU+ufF8/h4+MKPV4JRy2S+yKlCKW89vVy7ApDs3BZIub71zX0BEqweEBuzxyy5IfLQwAfMr9oDPw76LYc8z/zkZYe7a2X266dhHdwaSJMdtr0491NVTy4ICyRDZ7mo+dYGSEJW1LdTUqxIqrTulnGANAq79sKaa39Xm3K3e4epWn64/nsIVaKVgLUgSsihuzLU1jJBB98CpP2+6wILLvWqE6C9i8d955wBwoUjoVYqgB7U22Z6Uk3FJcwUXK5lKbCU=
    file_glob: true
    file: dist/pysonio*
    on:
      repo: jayme-github/pysonio
      tags: true
      condition: "$LATEST = true"
